#########################
## Sample Sass Lint File
#########################
# Linter Options
options:
  # Don't merge default rules
  merge-default-rules: true
# File Options
files:
  include: 'css/*.scss'
  ignore:
    - 'node_modules/**/*.*'
    - '_page/css/_bootstrap.scss'
